### ISSUE TITLE
 PostgreSQL server is not available. Waiting 5 seconds...

### ISSUE THREAD

**Issue by Ashwitha01** [cetic/helm-zabbix#11]
hi,
While i ran this helm chart on EKS cluster, pods are scheduled and running, but failed to obtain dashboard. 
logs says,

** Deploying Zabbix web-interface (Apache) with MySQL database
** Using POSTGRES_USER variable from ENV
** Using POSTGRES_PASSWORD variable from ENV
********************
* DB_SERVER_HOST: zabbix-postgresql
* DB_SERVER_PORT: 5432
* DB_SERVER_DBNAME: zabbix
* DB_SERVER_SCHEMA: public
********************
**** PostgreSQL server is not available. Waiting 5 seconds...
**** PostgreSQL server is not available. Waiting 5 seconds...

help me to solve the issue.

**Comment by aeciopires** [comment]
Hi @Ashwitha01! 

This problem is corrected in this Pull Request https://github.com/cetic/helm-zabbix/pull/14

**Comment by alexnuttinck** [comment]
The [new release](https://github.com/cetic/helm-zabbix/releases/tag/0.2.0) is now available. I close this issue.
