### ISSUE TITLE
[cetic/zabbix] Provide zabbixproxy.service.type

### ISSUE THREAD

**Issue by zhilyaev** [cetic/helm-zabbix#12]
**Describe the bug**
Values does not work

**Version of Helm and Kubernetes**:
3 helm
1.17 k8s

**What happened**:
zabbixproxy.service.type not working

**What you expected to happen**:
add zabbixproxy type to service.yaml

**Comment by aeciopires** [comment]
Hi @zhilyaev! 

This problem is corrected in this Pull Request https://github.com/cetic/helm-zabbix/pull/14

**Comment by alexnuttinck** [comment]
The [new release](https://github.com/cetic/helm-zabbix/releases/tag/0.2.0) is now available. I close this issue.

**Comment by richard-ostrochovsky** [comment]
Hello Friends, there is still note in https://github.com/cetic/helm-zabbix/blob/master/values.yaml:
`# **Zabbix proxy** not functional for the moment, work is still in progress.`

Is it still actual? If yes, can I help somehow to fix that?

**Comment by aeciopires** [comment]
Hi, @richard-ostrochovsky!

I don't think it works yet. From what I've been following in Pull Requests, this issue has not been resolved.
