### ISSUE TITLE
[cetic/zabbix] Support for zabbix 5

### ISSUE THREAD

**Issue by xeor** [cetic/helm-zabbix#13]
**Is your feature request related to a problem? Please describe.**
No way to run zabbix 5 on current helm chart

**Describe the solution you'd like**
Either updated chart to zabbix 5, or a way to configure the chart so it supports zabbix 5 container.

I got zabbix 5 working by changing the container ports (https://github.com/cetic/helm-zabbix/blob/master/templates/Web-deplyment.yaml#L50-L61) to 8080, and updating the images to one with zabbix 5, example `:centos-5.0-latest`. However, the port they use is `8080` not `80` which is hardcoded in the current chart.

**Describe alternatives you've considered**
Forking the chart making the small changes needed to run zabbix 5

**Comment by aeciopires** [comment]
Hi @xeor!

This problem is corrected in this Pull Request https://github.com/cetic/helm-zabbix/pull/14

**Comment by alexnuttinck** [comment]
The [new release](https://github.com/cetic/helm-zabbix/releases/tag/0.2.0) is now available. I close this issue.
