### ISSUE TITLE
DB_SERVER_PORT on the zabbixServer like zabbixweb

### ISSUE THREAD

**Issue by dnplkndll** [cetic/helm-zabbix#20]
DB_SERVER_PORT on the zabbixServer like zabbixweb

just a template parameter add request.

**Comment by dnplkndll** [comment]
https://github.com/cetic/helm-zabbix/pull/21

**Comment by aeciopires** [comment]
Hi @dnplkndll!

Thank you very much for your contribution.

As your Pull Request has been open for a long time, I took the initiative to include the solution in this other Pull Request. https://github.com/cetic/helm-zabbix/pull/35
