### ISSUE TITLE
[cetic/zabbix] possibility to configure custom environment variables

### ISSUE THREAD

**Issue by scoopex** [cetic/helm-zabbix#25]
The zabbix docker images provide the possibility to configure environment variables to fine-tune the behavior of zabbix server.

It would be nice to have the possibility to add custom environment variables for all pods.

https://hub.docker.com/r/zabbix/zabbix-server-pgsql

**Comment by scoopex** [comment]
Solved by https://github.com/cetic/helm-zabbix/pull/26

**Comment by scoopex** [comment]
Done

**Comment by ozhuang** [comment]
Can we have an example format of environment variables in `Values.yaml` ? 
I'm unable to set it right. Helm keep shouting for errors :(

**Comment by aeciopires** [comment]
Hi @ozhuang!

Fixed issue with this Pull Request https://github.com/cetic/helm-zabbix/pull/36 
Generated helm chart version 0.4.1.
