### ISSUE TITLE
[cetic/zabbix] Generate new release of chart

### ISSUE THREAD

**Issue by aeciopires** [cetic/helm-zabbix#28]
Hello, @AyadiAmen!

I merged some pull requests for the master branch. I don't have permission and I don't know the procedure to run Circle CI to generate a new version of the chart and publish in helm repo remote of cetic.

Could you do this or teach me?

I created the tag 0.3.3 and release v0.3.3

Copy @scoopex...

**Comment by banzo** [comment]
The CircleCI run is run automatically when the PR is merged, the 0.3.3 version is published at https://github.com/cetic/helm-charts/blob/gh-pages/zabbix/zabbix-0.3.3.tgz

can we close this issue?

**Comment by aeciopires** [comment]
Thank you @banzo! I didn't know this information. Yes, we can close this issue.
