### ISSUE TITLE
[cetic/zabbix] zabbix_agent2 support?

### ISSUE THREAD

**Issue by richard-ostrochovsky** [cetic/helm-zabbix#33]
Hello friends,

as Zabbix is doing new developments in **zabbix_agent2** more preferably than legacy **zabbix_agentd**, it would be also valuable to include support for https://hub.docker.com/r/zabbix/zabbix-agent2. Maybe it is already included in https://github.com/cetic/helm-zabbix/blob/master/templates/StatefulSet.yaml and tested with both generations (as they are quite similar from configuration point of view and interchangable) - in such case, it could be useful to include explicit note about this in README.

One significant difference is support of various plugins for monitoring e.g. MongoDB, etc.:
https://www.zabbix.com/documentation/current/manual/config/items/plugins#plugins_supplied_out-of-the-box

Please, let me know, if I could help somehow, if needed.

https://www.zabbix.com/documentation/current/manual/appendix/agent_comparison

Richard

**Comment by aeciopires** [comment]
Hi, @richard-ostrochovsky!

This is a really cool feature. Do you have the time and expertise to open a Pull Request that implements this functionality on the helm chart?

**Comment by richard-ostrochovsky** [comment]
Hi, @aeciopires ,

I hope, yes, over time, but for now I am still in K8S, Helm, etc. educational process, a newbie :) (although in ZBX being senior). So for now I started just this non-helm playground primarilly for my own educational purposes (work in progress) and I plan to play also with kubectl+kustomize a bit: https://github.com/richard-ostrochovsky/k8s-zabbix-proxy, with the goal to have full-feature ZBX proxy pod, with sidecar containers for specialities like usage of some zabbix_agent2 plugins, SNMP traps, JMX monitoring, ... maybe some of them in separate pods, still learning the concepts, what will be optimal ...

... about ZBX server, I am still not sure, if running it inside K8S is optimal for our particular case, as we need to monitor several K8S clusters, and monitoring server could be independent of them (we have multiple non-K8S ZBX instances, we need to consolidate, too).

**Comment by aeciopires** [comment]
Hi @richard-ostrochovsky!

I tested **zabbix-agent2** to work and installation is very simple with this helm chart. Just copy and customize the contents of the **values.yaml** file, replacing the zabbix-agent docker image by zabbix-agent2.

The changes are in this Pull Request: https://github.com/cetic/helm-zabbix/pull/35
