### ISSUE TITLE
[cetic/zabbix] SQLite support for zabbix_proxy

### ISSUE THREAD

**Issue by richard-ostrochovsky** [cetic/helm-zabbix#34]
Hello Friends,

in most cases, simpler SQLite-based proxy is enough, extra container with DB engine is not needed in such case.

Is it possible to use these helm charts to deploy https://hub.docker.com/r/zabbix/zabbix-proxy-sqlite3?

If yes, maybe we could explicitly describe it in the README.

Please, let me know, if I could help somehow, if needed.

Richard

**Comment by aeciopires** [comment]
Hello @richard-ostrochovsky!

From what I've seen the helm chart still doesn't support zabbix-proxy with SQLite. Your idea is cool. Do you have the time and expertise to open a Pull Request with the changes that implement this?

**Comment by aeciopires** [comment]
Hi @richard-ostrochovsky!

I tested it and managed to work **Zabbix-Proxy** with SQLite3. I removed zabbix-proxy support with MySQL.

The changes are in this Pull Request: https://github.com/cetic/helm-zabbix/pull/35
