### ISSUE TITLE
[cetic/zabbix] support for zabbix webservice

### ISSUE THREAD

**Issue by scoopex** [cetic/helm-zabbix#38]
Zabbix 5.4 provides a new features which provides automatic reports.

https://www.zabbix.com/documentation/5.4/en/manual/config/reports
https://www.zabbix.com/documentation/5.4/en/manual/appendix/install/web_service

It would be nice to have support for deploying the zabbix web_service

**Comment by aeciopires** [comment]
Hello @scoopex!

Sorry for the delay in responding.

Your order is very good. Personally, I haven't used this feature yet. I don't even know how to test.

Do you know a bit about helm and Kubernetes? If so, could you work on that and open a pull request adding this functionality? If so, I would greatly appreciate your contribution to this project.

Hugs and good week.

**Comment by aeciopires** [comment]
Hi @scoopex!

In the PR https://github.com/cetic/helm-zabbix/pull/54 @sa-ChristianAnton is implementing the solution
