### ISSUE TITLE
[cetic/zabbix] Simple ICMP check don't work

### ISSUE THREAD

**Issue by ravelund** [cetic/helm-zabbix#43]
Deploying basically the default chart for testing .

Simple ICMP ping check does not work.

![image](https://user-images.githubusercontent.com/20682689/154155646-5ddccaba-d2fa-4485-a0e2-467b63afad46.png)

tty to the container output:
zabbix@zabbix-zabbix-server-0:/$ ping 1.1.1.1
ping: socket: Address family not supported by protocol
zabbix@zabbix-zabbix-server-0:/$ ping4 1.1.1.1
ping4: socket: Operation not permitted
zabbix@zabbix-zabbix-server-0:/$ fping 1.1.1.1
fping: can't create socket (must run as root?)
zabbix@zabbix-zabbix-server-0:/$

**Comment by ravelund** [comment]
tracerout works
![image](https://user-images.githubusercontent.com/20682689/154156104-158249cd-0ada-43db-995a-0f61186ea747.png)

**Comment by aeciopires** [comment]
Hello @ravelund!

I think this is not a specific problem with the helm chart, but with the zabbix-server Docker image provided by Zabbix SIA and used in the helm chart.

I think the Zabbix server Docker image was generated without supporting these ping commands.

The Zabbix 6.0 image was released yesterday. I'm going to change the helm chart to use the new version and then we can check if this will be resolved.

**Comment by ravelund** [comment]
Hi. Thanks for a quick answer. I agree, i also think it is the docker image now.
I can test the new chart when it is ready :-)

**Comment by aeciopires** [comment]
Hello @ravelund!

The problem was in Docker Image. I tested with the tag ubuntu-6.0.0 and all command works.
