### ISSUE TITLE
[cetic/zabbix] Ability to add snmp mibs

### ISSUE THREAD

**Issue by MartinHell** [cetic/helm-zabbix#49]
Hi!

First of all thank you for creating this helm chart:) I've noticed that it currently doesn't seem to be possible to add snmp mibs to the zabbix proxy (or at least persist them). The zabbix-proxy and server containers supports adding mibs but they need to be placed in the /var/lib/zabbix/mibs directory (https://hub.docker.com/r/zabbix/zabbix-proxy-sqlite3 https://hub.docker.com/r/zabbix/zabbix-server-pgsql). Seeing as the container supports it I think it might make sense to add the option for mounting a PVC in the /var/lib/zabbix/mibs location for persistence.

It woldn't solve the issue of getting the mibs to the directory but at least they would be persisted. 

Now just adding persistence support might open up other issues. For instance if you'd scale out the zabbix-proxy you'd probably have to use a storageclass supporting readwritemany. There's probably other issues I'm not currently thinking about however so a discussion about it would be good.

**Is your feature request related to a problem? Please describe.**
Adding snmp mibs is currently not possibe or at least they will not be persisted on a container reboot or migration.

**Describe the solution you'd like**
As I see it there is two solution to this. 

1.  Add support for mounting a persistent volume in the containers
2. Add the option to mount mibs as a configmap (This might be a better solution since it would solve the issue of scaling out the zabbix-proxy)

**Describe alternatives you've considered**
An alternative solution to deal with this is to build your own docker image and deploy that instead. However I don't see this as a viable solution since you'd need to maintain builds for new zabbix releases and so on.

I guess having a discussion about this before trying to implement something would be good.

**Comment by fibbs** [comment]
With version 3.0.0 of this chart, all components got the ability to add additional volumes, for example with the `zabbixserver.extraVolumes` setting for the Zabbix server, and `zabbixserver.extraVolumeMounts` to mount these at any place into the container, such as the path for mibs mentioned by you. This opens freedom to either mount a persistent volume, or configmap.

I think this issue can be closed.

**Comment by sa-ChristianAnton** [comment]
In recently published version 3.0.0 of this chart, we have added the capability to add extraVolumes and extraVolumeMounts to every of the components deployed by this chart, by adding the appropriate yaml snippet into the values.yaml file.
I believe this also solves this issue.

**Comment by aeciopires** [comment]
I agree @sa-ChristianAnton.

@Lillecarl and @MartinHell can you test new version of chart and send us feedback. If necessary, other issue and pull request will can open. 

Have a nice weekend.
