### ISSUE TITLE
[cetic/zabbix] specific image tags for artifacts

### ISSUE THREAD

**Issue by scoopex** [cetic/helm-zabbix#62]
**Is your feature request related to a problem? Please describe.**

Sometimes it is necessary to use specific versions of zabbix docker images if there are bugs in recent versions.
A good example: https://support.zabbix.com/browse/ZBXNEXT-7778 (downgrading to 6.0.4 helps to solve the problem)

**Describe the solution you'd like**

Allow the definition of specific versions.

**Comment by aeciopires** [comment]
Hi @scoopex!

You can do it changing value in `zabbix_image_tag`  parameter.

In version 3.0.0 of chart, this parameter is applied to all Zabbix components to simplifier chart code.

**Comment by scoopex** [comment]
That's correct, but you cannot have different versions between components.
