### ISSUE TITLE
Add extra parameter to add extra containers with sidecar pattern

### ISSUE THREAD

**Issue by maxenced** [cetic/helm-zabbix#65]
Hi,

first, thanks for all the work you did with this helm chart ! 
For some reason (we use consul as resolver) we need a custom extra container to be used within our zabbix-server/web pods.

Would you be able to add an extra parameter like `extra_containers` so that we can define any extra needed containers using sidecar pattern ? Does not look like a big change and would help a lot extending your chart.

Maxence

**Comment by aeciopires** [comment]
Hi @maxenced!

Thanks for using this helm chart! :-)

You would like that be implemented this [1](https://github.com/criblio/helm-charts/blob/master/common_docs/EXTRA_EXAMPLES.md#using-extracontainers-) or this [2](https://github.com/criblio/helm-charts/blob/master/common_docs/EXTRA_EXAMPLES.md#using-extrainitcontainers-) or both?

Do you can share an example of config that you usually use?

**Comment by maxenced** [comment]
Well ... i checked the code before asking here, can't understand why I did  not see that :/ Thank you !

**Comment by aeciopires** [comment]
Ok @maxenced!
I will do it using the same implementation (list of config) of the extra Containers.
That help you?

**Comment by aeciopires** [comment]
I had seen your change, but I was wondering if you still need the extraInitContainer or if you can solve it the way the helm chart is implemented.

**Comment by maxenced** [comment]
extraInitContainer won't solve it as i need the extra container to be started at same time than your init container, but init containers are started one at a time. For now, we will just avoid using more than one replica so that there is no init container at all. I still have another issue with dns config, but will open a new issue for it ;)
