### ISSUE TITLE
Allow extra config (or dnspolicy/dnsconfig) to be added for every pod

### ISSUE THREAD

**Issue by maxenced** [cetic/helm-zabbix#66]
This is for the same usecase than #65 . We are using a custom dns (with consul) and need our server and web containers to resolve using local resolver (which is a dnsmasq container inside same pod).

Right now, there is no way to customize the needed spec attributes, ie:

* `dnsPolicy`
* `dnsConfig`

Any chance you can either add them in spec (and make them customizable) or, more generic solution, add something like `extraSpecConfig` to be able to add any config not supported by chart ?

**Comment by aeciopires** [comment]
Hey, @maxenced!

I quickly searched on Google and didn't find a helm chart that did this, I even saw some examples but in practice it's like a configMap to fill in a configuration file.

Do you have an example helm chart, or do you have an example of what this configuration would look like in practice so I can understand what can be done?

**Comment by aeciopires** [comment]
Hi @maxenced!

extraVolumeMounts and extraVolume using ConfigMap do not resolve your problem?

**Comment by maxenced** [comment]
I don't think so, or it would be a dirty workaround (like overriding /etc/resolv.conf with a volume).
I think your solution in #67 should do the trick. We'll test it quickly. 

Thank you for your fast answers !

**Comment by aeciopires** [comment]
Resolved in PR #67
