### ISSUE TITLE
Add permission in repository

### ISSUE THREAD

**Issue by aeciopires** [cetic/helm-zabbix#68]
Hello @banzo, @AyadiAmen and @alexnuttinck!

Could you please add @sa-ChristianAnton and me as administrators of this repository? 

I cannot perform any administrative tasks in the Settings menu.

Thanks for your attention.

**Comment by banzo** [comment]
Hello @aeciopires,

I'll check with management. This may take some time due to vacations, in the meantime feel free to tell me what needs to be done and I will do it for you.

FYI we are discussing internally which charts we can keep at CETIC. Would you be interested to take over this chart completely? (i.e. fork it and publish it in you own/Sensedia's chart repo?).

**Comment by aeciopires** [comment]
Good Morning, @banzo!

Thank you for your answer.

There is currently nothing urgent to be done. I'd just like to set up sending emails to @sa-ChristianAnton whenever someone opens a issue or Pull Request. Today, even though he is a maintainer, he only gets paid if I mention him manually.

About keeping the git repo and helm repo, I'm interested. But to not have this same situation in the future, I prefer to fork my personal account and configure the helm repo directly on GitHub and still configure the integration with Artifact Hub.

If you agree, I can already provide and write a notice about it.

Have a good week.

**Comment by banzo** [comment]
Hello @aeciopires I have the confirmation, please go ahead. 
Let me know if/how I can help.

**Comment by aeciopires** [comment]
Hello @banzo!

Thank you very much for help and confirmation.
I will work in this task. 
I think to create an independent organization in Github to keep  the aspect of community care of helm chart. I will can to do it after we resolve and closed the issues opened and after publish the new version. 

Don't worry. I will write a message about the migration of repository and thanking you for all the support given by cetic in the early development of this helm chart.

Have a nice weekend.

CC: @sa-ChristianAnton
