### ISSUE TITLE
[cetic/zabbix] Please add support for MySQL Database

### ISSUE THREAD

**Issue by scila1996** [cetic/helm-zabbix#75]
Hi, we are planing to use MySQL. Please update template for it !

Thank you 😁

**Comment by aeciopires** [comment]
Hello @scila1996!

While Zabbix supports other database types besides PostgreSQL, it takes a lot of work to create and maintain a helm chart that supports multiple database types as well as the various types of possible configurations supported by each database. Also, it would be a lot of work to test all changes to the chart against other databases.

There is an initiative by Zabbix SIA itself to create its own helm chart. Maybe they will evolve to install Zabbix Server and other components with MySQL support. https://git.zabbix.com/projects/ZT/repos/kubernetes-helm/browse

Feel free to open a pull request that supports MySQL. See how it was done for PostgreSQL and try to maintain or improve the source code quality standard.

**Comment by aeciopires** [comment]
CC: @sa-ChristianAnton For your information.
