### ISSUE TITLE
Permission issue when enabling persistance

### ISSUE THREAD

**Issue by SalmanIsha** [cetic/helm-zabbix#77]
Hello,

I have almost done the bare metal installation of this helm chart except enabling the existing pv claim. And then it breaks my deployment. The postgres pod is getting error like below:

chown: changing ownership of '/var/lib/postgresql/data/pgdata': Operation not permitted

I am very much confused where I am doing the mistakes. If I add securityContext ( runasuser: 65534) in the values.yaml file the postgres pod works fine but then the zabbix web can't up the nginx service.

Anyone have idea what is going wrong here?

**Comment by aeciopires** [comment]
Hi @SalmanIsha !

This project is no longer supported.
The code was migrated for https://github.com/zabbix-community/helm-zabbix
I see that you have already opened an issue in the new project. We'll keep talking there.
